---
- name: Deploy OpenNebula AIO
  hosts: frontend
  become: true
  collections:
    - opennebula.deploy

  roles:
    - role: opennebula.deploy.infra
    - role: opennebula.deploy.opennebula
    - role: opennebula.deploy.gui
