---
- name: Deploy OpenNebula AIO
  hosts: frontend
  become: true

  collections:
    - opennebula.deploy

  roles:
    - opennebula.deploy.precheck
    - opennebula.deploy.infra
    - opennebula.deploy.opennebula
    - opennebula.deploy.gui
    - opennebula.deploy.network
